In [1]:
import numpy
import cv2

In [42]:
#to convert an image to a numpy object
im_g=cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
#to convert a numpy object to an image
cv2.imwrite("newsmallgray.png", im_g)

True

In [7]:
#to convert an image to a numpy object
#second argument is 1 if color conversion
im_g=cv2.imread("194.jpg", 1)
im_g

array([[[232, 231, 211],
        [232, 231, 211],
        [234, 233, 212],
        ...,
        [226, 222, 198],
        [226, 222, 198],
        [226, 222, 198]],

       [[233, 232, 212],
        [232, 231, 211],
        [236, 235, 214],
        ...,
        [226, 222, 198],
        [224, 220, 196],
        [223, 219, 195]],

       [[224, 223, 203],
        [223, 222, 202],
        [227, 226, 205],
        ...,
        [228, 224, 200],
        [227, 223, 199],
        [226, 222, 198]],

       ...,

       [[114, 117,  92],
        [121, 122, 102],
        [118, 121, 106],
        ...,
        [173, 214, 216],
        [171, 212, 214],
        [171, 212, 214]],

       [[120, 121,  95],
        [118, 120,  98],
        [113, 114,  98],
        ...,
        [174, 215, 217],
        [172, 213, 215],
        [172, 213, 215]],

       [[120, 122,  93],
        [111, 114,  89],
        [107, 108,  92],
        ...,
        [174, 215, 217],
        [173, 214, 216],
        [173, 214, 216]]

In [8]:
#to convert a numpy object to an image
cv2.imwrite("new194.jpg", im_g)

True

In [43]:
im_g2=([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]],)
im_g2

([[[187, 187, 187],
   [158, 158, 158],
   [104, 104, 104],
   [121, 121, 121],
   [143, 143, 143]],
  [[198, 198, 198],
   [125, 125, 125],
   [255, 255, 255],
   [255, 255, 255],
   [147, 147, 147]],
  [[209, 209, 209],
   [134, 134, 134],
   [255, 255, 255],
   [97, 97, 97],
   [182, 182, 182]]],)

In [44]:
#to convert a numpy object to an image
cv2.imwrite("newsmallgray.png", im_g)

True

In [45]:
a=[1,2,3]

In [46]:
a[0:1]

[1]

In [47]:
#to convert an image to a numpy object
im_g=cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
#slice - get first two rows
#im_g[0:2]
#slice - get first two rows and third and fourth columns
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [51]:
im_g.shape

(3, 5)

In [54]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [56]:
#to transpose values
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [57]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [58]:
#to stack arrays pass them as a tuple
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [62]:
#to stack horizontally
#ims=numpy.hstack((im_g, im_g))
#pass multiples as long as they are in tuple form
ims=numpy.hstack((im_g, im_g, im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [63]:
#to stack vertically
ims=numpy.vstack((im_g, im_g, im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [66]:
#to split 
lst = numpy.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]